feat: adding modal and dialog packages
project44/manifest pull request #254
Opened 2023-02-22 19:41 UTC by bclark-p44

#DES-475
#DES-476

## 📝 Description

Adding modal and dialog components.

## Screenshots

> Please provide screenshots for any visual changes

## Merge checklist

- [ ] Added/updated tests
- [ ] Added changeset

2023-02-22 19:43 UTC, bclark-p44 commented on packages/react/components/overlay/src/Overlay.tsx
> +    <ReactAriaOverlay portalContainer={containerRef?.current as Element}>
Using the react-aria overlay element to ensure focus scope is handled correctly.

2023-02-23 18:07 UTC, andrea-p44 requested changes
For the dialog - in order to keep consistent padding with our card, modal, and action card, let's bump it up from 16px to 24px. (That's on me, since I originally designed it with 16) Already changed in the Figma.
For the modal - it has a blue ring around it when I open it. Also, just want to confirm that the padding is 24? It looks like it is, but I can't measure it.

2023-02-23 18:11 UTC, bclark-p44 commented
I'll update both to use 24px and remove the blue outline

2023-03-03 17:03 UTC, andrea-p44 approved these changes

2023-03-06 20:58 UTC, merged